// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoFJfAH8COcjbC9moV7aSbevDh6mdngU',
    appId: '1:584993857235:web:790a75017a6f38024d7e26',
    messagingSenderId: '584993857235',
    projectId: 'planttracker-fb02b',
    authDomain: 'planttracker-fb02b.firebaseapp.com',
    databaseURL: 'https://planttracker-fb02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planttracker-fb02b.firebasestorage.app',
    measurementId: 'G-7PV6FV3EJ2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFiQNDRtz3_YAGv57kH0TaU38pCfEIU4',
    appId: '1:584993857235:ios:08cd80685826b0cb4d7e26',
    messagingSenderId: '584993857235',
    projectId: 'planttracker-fb02b',
    databaseURL: 'https://planttracker-fb02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planttracker-fb02b.firebasestorage.app',
    iosBundleId: 'com.example.plantTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjFiQNDRtz3_YAGv57kH0TaU38pCfEIU4',
    appId: '1:584993857235:ios:08cd80685826b0cb4d7e26',
    messagingSenderId: '584993857235',
    projectId: 'planttracker-fb02b',
    databaseURL: 'https://planttracker-fb02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planttracker-fb02b.firebasestorage.app',
    iosBundleId: 'com.example.plantTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwoFJfAH8COcjbC9moV7aSbevDh6mdngU',
    appId: '1:584993857235:web:3b87e1159b0c4b024d7e26',
    messagingSenderId: '584993857235',
    projectId: 'planttracker-fb02b',
    authDomain: 'planttracker-fb02b.firebaseapp.com',
    databaseURL: 'https://planttracker-fb02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planttracker-fb02b.firebasestorage.app',
    measurementId: 'G-LYXTKEJ0P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UK7MFoYoFAyNLJHStQ6cDfFaGaEzMag',
    appId: '1:584993857235:android:453c7d5886fbb96c4d7e26',
    messagingSenderId: '584993857235',
    projectId: 'planttracker-fb02b',
    databaseURL: 'https://planttracker-fb02b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planttracker-fb02b.firebasestorage.app',
  );

}